@startuml

package "App (Flask)" {
  [Flask Server] --> [main.py]
  [Flask Server] --> [Templates]
  [Flask Server] --> [Config.json]
  [Flask Server] --> [DataManager] : uses
  [Flask Server] --> [JSONDataSource] : uses
  [Flask Server] --> [instances.json]
  [Flask Server] --> [analytics.json]
}

package "Templates" {
  [index.html]
  [config.html]
  [feedback.html]
}

package "Data Management (Singleton)" {
  [DataManager] --> [DataSource] : uses
  [DataManager] --> [instances.json]
  [DataManager] --> [analytics.json]
  [DataManager] --> [Config.json]
  [JSONDataSource] --> [DataSource] : implements
}

[Flask Server] --> [DataManager] : interacts with

@enduml
